# Before publishing, all of these versions need to be pinned!
name: synthetic-observables
channels:
- defaults
- conda-forge
dependencies:
- python
- numpy
- numba
- scipy
- matplotlib
- h5py
- astropy
- sunpy
- dask
- distributed
- yt
- seaborn
- scikit-learn
- pip:
  - plasmapy
  - hissw
  - git+https://github.com/Cadair/texfigure.git
  - git+git://github.com/wtbarnes/fiasco.git
  - git+git://github.com/wtbarnes/synthesizAR.git